### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by ghost** [ObelusFamily/Anythink-Market-4mfyhv44#1]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. 

Try and reproduce this issue locally by creating some imageless items, and then make sure that the frontend always renders a placeholder image. 

You can find a placeholder image in the repository, it's called `placeholder.png`.

Once you fix this issue, open a PR and attach a screenshot of the fixed UI.

**Comment by yprimakov** [comment]
![image](https://user-images.githubusercontent.com/1775746/209738227-2652e36f-6741-44e9-91ba-d743dc931031.png)
